# Importing Numpy

In [52]:
import numpy as np

# Question 1

In [53]:
vector = np.random.randint(low=0, high=11, size=5)
vector

array([3, 3, 5, 4, 4])

# Question 2

In [54]:
vector1 = np.arange(15, 55)[1: -1]
vector1

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

# Question 3

In [58]:
vector2 = np.random.rand(1000)
average = np.mean(vector2)
variance = np.var(vector2)
std_dev = np.std(vector2)

In [60]:
print("Average = ", average)
print("Variance = ", variance)
print("Standard Deviation = ", std_dev)

Average =  0.49990497118972926
Variance =  0.08683247112797922
Standard Deviation =  0.29467349919526054


# Question 4

In [72]:
arr = np.random.randint(11, size=(3,3))
arr

array([[ 8,  9,  6],
       [ 3,  6,  8],
       [10,  2,  9]])

In [91]:
rows = np.cumsum(arr, axis=0)
rows

array([[ 8,  9,  6],
       [11, 15, 14],
       [21, 17, 23]], dtype=int32)

In [101]:
cols = np.cumsum(arr, axis=1)[:2, :3]
cols

array([[ 8, 17, 23],
       [ 3,  9, 17]], dtype=int32)

# Question 5

In [106]:
a = np.array([[1,0],[0,1]])
b = np.array([[1,2],[3,4]])


In [111]:
c = np.dot(a,b)
c

array([[1, 2],
       [3, 4]])