# Importing numpy

In [1]:
import numpy as np

# Section A

Creating 2x3 matrix 

In [2]:
a = np.array([[1,2,3],[4,5,6]])

Multiplying matrix by scaler

In [3]:
b = a * 2
print(b)

[[ 2  4  6]
 [ 8 10 12]]


# Section B

Creating a 3x3 identity matrix

In [5]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Section C

Creating a 1-D array

In [10]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,
                   11,12,13,14,15,16,17,18,19,20,
                   21,22,23,24,25,26,27])

Converting matrix from 1-D to 3-D

In [11]:
array2 = array1.reshape((3,3,3))
array2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

# Section D

Creating 2-D array

In [4]:
a = ([[1,2,3],[4,5,6]])
b = ([[7,8,9],[10,11,12]])

Horizontal Stack

In [6]:
c = np.hstack((a,b))
print(c)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Vertiacal Stack

In [8]:
c = np.vstack((a,b))
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Equally Spaced Sequence

In [14]:
sqc = np.arange(0, 101, 5)
print(sqc)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]
