In [4]:
import numpy as np

In [5]:
ones = np.ones((5, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
zeros = np.zeros((3, 3))
zeros[1, 1] = 9
zeros

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [7]:
ones[1:4, 1:4] = zeros
ones

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
test9 = np.full((9, 9), 9)
test9[1:8, 1:8] = 8
test9[2:7, 2:7] = 7
test9[3:6, 3:6] = 6
test9[4,4] = 5

In [9]:
test9

array([[9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 8, 8, 8, 8, 8, 8, 8, 9],
       [9, 8, 7, 7, 7, 7, 7, 8, 9],
       [9, 8, 7, 6, 6, 6, 7, 8, 9],
       [9, 8, 7, 6, 5, 6, 7, 8, 9],
       [9, 8, 7, 6, 6, 6, 7, 8, 9],
       [9, 8, 7, 7, 7, 7, 7, 8, 9],
       [9, 8, 8, 8, 8, 8, 8, 8, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9]])